export enum IndustryType {
  Agriculture = 'agriculture',
  Mining = 'mining',
  Manufacturing = 'manufacturing',
  Utilities = 'utilities',
  Construction = 'construction',
  WholesaleRetail = 'wholesale_retail',
  Transportation = 'transportation',
  AccommodationCatering = 'accommodation_catering',
  InformationTechnology = 'information_technology',
  Finance = 'finance',
  RealEstate = 'real_estate',
  ProfessionalServices = 'professional_services',
  ScientificResearch = 'scientific_research',
  WaterConservancy = 'water_conservancy',
  ResidentServices = 'resident_services',
  Education = 'education',
  Healthcare = 'healthcare',
  CultureEntertainment = 'culture_entertainment',
  PublicManagement = 'public_management',
  InternationalOrganizations = 'international_organizations',
  Other = 'other',
}
