/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElWatermark: typeof import('element-plus/es')['ElWatermark']
    HistoryTab: typeof import('./src/components/HistoryTab.vue')['default']
    HistoryTabItem: typeof import('./src/components/HistoryTabItem.vue')['default']
    'IBx:file': typeof import('~icons/bx/file')['default']
    'IFa6Regular:floppyDisk': typeof import('~icons/fa6-regular/floppy-disk')['default']
    'IFaSolid:user': typeof import('~icons/fa-solid/user')['default']
    'IGravityUi:thunderbolt': typeof import('~icons/gravity-ui/thunderbolt')['default']
    'IGridicons:noticeOutline': typeof import('~icons/gridicons/notice-outline')['default']
    'IIconParkOutline:coordinateSystem': typeof import('~icons/icon-park-outline/coordinate-system')['default']
    'IIon:close': typeof import('~icons/ion/close')['default']
    'IMingcute:downLine': typeof import('~icons/mingcute/down-line')['default']
    'IOcticon:people16': typeof import('~icons/octicon/people16')['default']
    'IOi:collapseLeft': typeof import('~icons/oi/collapse-left')['default']
    'IOi:collapseRight': typeof import('~icons/oi/collapse-right')['default']
    'IPh:userBold': typeof import('~icons/ph/user-bold')['default']
    'IPh:warningBold': typeof import('~icons/ph/warning-bold')['default']
    'IRadixIcons:accessibility': typeof import('~icons/radix-icons/accessibility')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
