import { PayType, TransactionMode, type IDemand } from '@/types/demand'

export const demands: IDemand[] = [
  {
    id: 1,
    title: '智能客流分析系统',
    description: '实时监测景区游客密度，优化流量管理。',
    publisher: 'ABC 科技公司',
    budget: 100000,
    transactionType: { mode: TransactionMode.Pitch },
    expectedDeliveryDate: '2024-01-10',
    tags: ['开发', 'Web', '技术'],
  },
  {
    id: 2,
    title: '旅游消费者行为画像',
    description: '深入分析游客偏好，提升个性化服务体验。',
    publisher: 'XYZ 数据公司',
    budget: 150000,
    transactionType: {
      mode: TransactionMode.Tender,
      payType: PayType.ByWorkTime,
    },
    expectedDeliveryDate: '2024-02-15',
    tags: ['人工智能', '机器学习', '数据'],
  },
  {
    id: 3,
    title: '景区运营数据可视化平台',
    description: '直观展示运营数据，辅助决策，提升效率。',
    publisher: 'MNO 市场营销公司',
    budget: 200000,
    transactionType: {
      mode: TransactionMode.Tender,
      payType: PayType.ByFixedPrice,
    },
    expectedDeliveryDate: '2024-03-05',
    tags: ['咨询', '营销', '战略'],
  },
  {
    id: 4,
    title: '旅游市场趋势预测工具',
    description: '预测市场趋势，为旅游企业战略规划提供支持。',
    publisher: 'DEF 企业解决方案',
    budget: 250000,
    transactionType: { mode: TransactionMode.Pitch },
    expectedDeliveryDate: '2024-01-20',
    tags: ['云计算', '迁移', 'IT'],
  },
  {
    id: 5,
    title: '智慧景区规划与管理服务',
    description: '利用大数据优化景区规划，提升游客满意度。',
    publisher: 'GHI 移动开发公司',
    budget: 300000,
    transactionType: { mode: TransactionMode.Pitch },
    expectedDeliveryDate: '2024-02-25',
    tags: ['开发', '移动应用', '设计'],
  },
  {
    id: 6,
    title: '旅游产品推荐算法服务',
    description: '基于用户行为，智能推荐旅游产品和服务。',
    publisher: 'JKL 培训服务公司',
    budget: 80000,
    transactionType: { mode: TransactionMode.Pitch },
    expectedDeliveryDate: '2024-04-10',
    tags: ['培训', '技术', '软技能'],
  },
]
