import { CompanySize, IndustryType, UserStatus, UserType } from '@/constants/mapData/user'
import type { IEnterpriseUser } from '@/types/user'

export const enterpriseUsers: IEnterpriseUser[] = [
  {
    id: 1,
    email: 'enterprise1@example.com',
    userType: UserType.Enterprise,
    status: UserStatus.ACTIVE,
    createTime: '2024-12-01T10:00:00Z',
    updateTime: '2024-12-01T10:00:00Z',
    enterpriseName: 'Tech Solutions Inc.',
    enterpriseDescription: 'A leading provider of tech solutions.',
    registrationNumber: 'ENT123456',
    contactPersonName: 'John Doe',
    contactPersonTitle: 'CEO',
    contactPhoneNumber: '123-456-7890',
    enterpriseAddress: '123 Tech Street, Silicon Valley, CA',
    industryType: IndustryType.InformationTechnology,
    companySize: CompanySize.Large
  },
  {
    id: 2,
    email: 'enterprise2@example.com',
    userType: UserType.Enterprise,
    status: UserStatus.PENDING,
    createTime: '2024-12-02T10:30:00Z',
    updateTime: '2024-12-02T10:30:00Z',
    enterpriseName: 'Green Energy Ltd.',
    enterpriseDescription: 'Promoting sustainable energy solutions.',
    registrationNumber: 'ENT654321',
    contactPersonName: 'Emily Clark',
    contactPersonTitle: 'COO',
    contactPhoneNumber: '234-567-8901',
    enterpriseAddress: '456 Green Avenue, New York, NY',
    industryType: IndustryType.Utilities,
    companySize: CompanySize.Medium
  },
  {
    id: 3,
    email: 'enterprise3@example.com',
    userType: UserType.Enterprise,
    status: UserStatus.SUSPENDED,
    createTime: '2024-11-25T14:00:00Z',
    updateTime: '2024-11-25T14:00:00Z',
    enterpriseName: 'FoodCorp',
    enterpriseDescription: 'A global food supply chain company.',
    registrationNumber: 'ENT112233',
    contactPersonName: 'John Doe',
    contactPersonTitle: 'Director',
    contactPhoneNumber: '345-678-9012',
    enterpriseAddress: '789 Food Road, Chicago, IL',
    industryType: IndustryType.Manufacturing,
    companySize: CompanySize.Large
  },
  {
    id: 4,
    email: 'enterprise4@example.com',
    userType: UserType.Enterprise,
    status: UserStatus.ACTIVE,
    createTime: '2024-11-10T09:30:00Z',
    updateTime: '2024-11-10T09:30:00Z',
    enterpriseName: 'EcoConstructions',
    enterpriseDescription: 'Building green and sustainable buildings.',
    registrationNumber: 'ENT998877',
    contactPersonName: 'Emily Clark',
    contactPersonTitle: 'Founder',
    contactPhoneNumber: '456-789-0123',
    enterpriseAddress: '321 Eco Lane, San Francisco, CA',
    industryType: IndustryType.Construction,
    companySize: CompanySize.Medium
  },
  {
    id: 5,
    email: 'enterprise5@example.com',
    userType: UserType.Enterprise,
    status: UserStatus.ACTIVE,
    createTime: '2024-11-05T11:00:00Z',
    updateTime: '2024-11-05T11:00:00Z',
    enterpriseName: 'MediaWave',
    enterpriseDescription: 'Innovative media and entertainment company.',
    registrationNumber: 'ENT556677',
    contactPersonName: 'Chris Lee',
    contactPersonTitle: 'CTO',
    contactPhoneNumber: '567-890-1234',
    enterpriseAddress: '123 Wave Avenue, Los Angeles, CA',
    industryType: IndustryType.CultureEntertainment,
    companySize: CompanySize.Small
  },
  {
    id: 6,
    email: 'enterprise6@example.com',
    userType: UserType.Enterprise,
    status: UserStatus.PENDING,
    createTime: '2024-12-03T08:45:00Z',
    updateTime: '2024-12-03T08:45:00Z',
    enterpriseName: 'Global Logistics',
    enterpriseDescription: 'Providing international logistics services.',
    registrationNumber: 'ENT778899',
    contactPersonName: 'John Doe',
    contactPersonTitle: 'VP of Operations',
    contactPhoneNumber: '678-901-2345',
    enterpriseAddress: '432 Logistics Park, Dallas, TX',
    industryType: IndustryType.Transportation,
    companySize: CompanySize.Large
  },
  {
    id: 7,
    email: 'enterprise7@example.com',
    userType: UserType.Enterprise,
    status: UserStatus.ACTIVE,
    createTime: '2024-11-12T10:20:00Z',
    updateTime: '2024-11-12T10:20:00Z',
    enterpriseName: 'AquaPur',
    enterpriseDescription: 'Water purification and distribution company.',
    registrationNumber: 'ENT445566',
    contactPersonName: 'Emily Clark',
    contactPersonTitle: 'Chief Engineer',
    contactPhoneNumber: '789-012-3456',
    enterpriseAddress: '654 Aqua Road, Miami, FL',
    industryType: IndustryType.WaterConservancy,
    companySize: CompanySize.Medium
  },
  {
    id: 8,
    email: 'enterprise8@example.com',
    userType: UserType.Enterprise,
    status: UserStatus.SUSPENDED,
    createTime: '2024-11-18T16:00:00Z',
    updateTime: '2024-11-18T16:00:00Z',
    enterpriseName: 'FashionCo',
    enterpriseDescription: 'Leading fashion retailer.',
    registrationNumber: 'ENT334455',
    contactPersonName: 'John Doe',
    contactPersonTitle: 'Brand Manager',
    contactPhoneNumber: '890-123-4567',
    enterpriseAddress: '987 Fashion Street, Paris, France',
    industryType: IndustryType.WholesaleRetail,
    companySize: CompanySize.Small
  },
  {
    id: 9,
    email: 'enterprise9@example.com',
    userType: UserType.Enterprise,
    status: UserStatus.ACTIVE,
    createTime: '2024-12-04T09:10:00Z',
    updateTime: '2024-12-04T09:10:00Z',
    enterpriseName: 'FinTech Solutions',
    enterpriseDescription: 'Revolutionizing financial services with technology.',
    registrationNumber: 'ENT223344',
    contactPersonName: 'Emily Clark',
    contactPersonTitle: 'Head of Innovation',
    contactPhoneNumber: '123-789-4560',
    enterpriseAddress: '321 FinTech Plaza, London, UK',
    industryType: IndustryType.Finance,
    companySize: CompanySize.ExtraLarge
  },
  {
    id: 10,
    email: 'enterprise10@example.com',
    userType: UserType.Enterprise,
    status: UserStatus.PENDING,
    createTime: '2024-12-02T07:30:00Z',
    updateTime: '2024-12-02T07:30:00Z',
    enterpriseName: 'RetailWorks',
    enterpriseDescription: 'Online retail platform for consumer goods.',
    registrationNumber: 'ENT667788',
    contactPersonName: 'Chris Lee',
    contactPersonTitle: 'Customer Relations Manager',
    contactPhoneNumber: '234-567-8901',
    enterpriseAddress: '123 Retail Road, Toronto, Canada',
    industryType: IndustryType.WholesaleRetail,
    companySize: CompanySize.Medium
  }
]
