import { ActiveStatus } from '@/constants/mapData'
import type { IOption } from '@/types/common'
import type { IScene } from '@/types/scene'

export const sceneOptions: IOption[] = [
  {
    value: 1,
    label: '场景1'
  },
  {
    value: 2,
    label: '场景2'
  },
  {
    value: 3,
    label: '场景3'
  }
]

export const scenes: IScene[] = [
  {
    id: 1,
    title: '三教庙数字剧游场景',
    company: {
      id: 1,
      name: '北京嘉联科技有限公司'
    },
    summary:
      '数字剧游场景主要面向5-12岁青少年及亲子家庭，在公园、景点、场馆、商业、乡村、古镇等各类场所制作开发“微信小程序+实景线索+剧情任务”形式的沉浸式剧本游戏活动，让亲子出行变得更有趣味性和知识性。通过活动，既可增进亲子关系，又能引导孩子锻炼体能、学习知识、训练思维、培养品格。真正做到寓教于乐、玩中收获。',
    coverImageUrl: 'http://10.105.31.40:9001/img/11.webp',
    headerImageUrl: new URL('@/assets/placeholder/productDefault.png', import.meta.url).href,
    status: ActiveStatus.Active,
    isOuterLink: false,
    content: `
     <p class="docData;DOCY;v5;3348;BQiAAgAAEYQCAAAGiAIAAAPSDAAABeAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARgoAAAAeAwAAAVUAAAABBgYAAAAmBIACAAAJBgAAAAAaBjcAAAAEBgQAAAD/TotbBQYEAAAA/06LWwcGBAAAAP9Oi1sGBgQAAAD/TotbEwECCAQgAAAAFgQgAAAAGwYAAAAAAr8CAAAFCgAAAAEAAAAACAAAAAAXHAAAAAAEAAAAAAAAAAEOAAAAXwBHAG8AQgBhAGMAawAFCgAAAAEAAAAACAAAAAAYCQAAAAAEAAAAAAAAAAVyAAAAAVcAAAAEBgQAAAD/TotbBQYEAAAA/06LWwcGBAAAAP9Oi1sGBgQAAAD/TotbEwECCAQgAAAAFgQgAAAAGQYKAAAAZQBuAC0AVQBTABsGCgAAAHoAaAAtAEMATgAIEQAAAAAMAAAAcGVXW2dSOG46V29mBWoBAAABNwAAAAQGBAAAAP9Oi1sFBgQAAAD/TotbBwYEAAAA/06LWwYGBAAAAP9Oi1sTAQIIBCAAAAAWBCAAAAAIKQEAAAAkAQAAO06BiWKXEVQ1AC0AMQAyAIFcUpcRXHReylOyTlBbtlutXgz/KFdsUe1WATBvZrlwATA6V4aZATBGVRpOATBhTlFnATDkU0eVSXsEVHt8OldAYjZSXE8AX9FTHCCuX+FPD1wLeo9eKwCeW29mv34ifSsAZ1LFYPtOoVIdIGJfD1+EdolseG0PX2dSLGc4bg9iO22oUgz/qYuyTlBb+lFMiNhTl1/0Zglno41zVCdgjFTld8aLJ2ACMBqQx487bahSDP/iZe9Tnljbj7JOUFtzUft8DP/IU/2AFV/8W2lbUFs7lbxwU0/9gAEwZltgTuV3xosBMK2Lw34dYPR+ATD5V3tRwVQ8aAIwH3dja1pQMFLTW1lljk5QTgEwqXMtTjZlt4MCMAVBAAAAATcAAAAEBgQAAAD/TotbBQYEAAAA/06LWwcGBAAAAP9Oi1sGBgQAAAD/TotbEwECCAQgAAAAFgQgAAAACAAAAAAFQQAAAAE3AAAABAYEAAAA/06LWwUGBAAAAP9Oi1sHBgQAAAD/TotbBgYEAAAA/06LWxMBAggEIAAAABYEIAAAAAgAAAAAAHQCAAABVQAAAAEGBgAAACYEgAIAAAkGAAAAABoGNwAAAAQGBAAAAP9Oi1sFBgQAAAD/TotbBwYEAAAA/06LWwYGBAAAAP9Oi1sTAQIIBCAAAAAWBCAAAAAbBgAAAAACFQIAAAWEAQAAATcAAAAEBgQAAAD/TotbBQYEAAAA/06LWwcGBAAAAP9Oi1sGBgQAAAD/TotbEwECCAQgAAAAFgQgAAAACEMBAAAAPgEAAJ5bb2ZwZVdbZ1I4bo2HZVGGTmdSxWABMDhuD2IBMOOJHIwBMJ5bb2aMVJJOqFKUTipOc1EulUNRIH0M/2lbUFsakMePjFsQYgBO+3wXUvtOoVIM/xFjGGLqgfFdhHZ6ZmdhjFTHUhRsDP8NTsVOqYvWTuxOH2HXUzBSklFploR2OlLAbwz/2I/vU+VOLl6pUtZO7E7QY0dT44mzUe6VmJiEdv2Am1IM/55YOl/iVh+WCFRcT4R2vnxeeQIwnltvZnBlV1tnUjhuDU7FTsVOL2YATj5rOG4PYgz/9GYvZgBOPmtZZbKA5V13UQz/6GUoVxqQx4+jjXNUhHa5ZQ9fDP8VX/xbaVtQW+xOcI36UbZb6JWiYyJ9H3eeW4R2Fk5MdQz/O5W8cNZO7E6Eduxyy3onYIxUApCUXv2Am1ICMAVBAAAAATcAAAAEBgQAAAD/TotbBQYEAAAA/06LWwcGBAAAAP9Oi1sGBgQAAAD/TotbEwECCAQgAAAAFgQgAAAACAAAAAAFQQAAAAE3AAAABAYEAAAA/06LWwUGBAAAAP9Oi1sHBgQAAAD/TotbBgYEAAAA/06LWxMBAggEIAAAABYEIAAAAAgAAAAAAKUEAAABdQAAAAEGBgAAACYEgAIAAAkGAAAAABoGVwAAAAQGBAAAAP9Oi1sFBgQAAAD/TotbBwYEAAAA/06LWwYGBAAAAP9Oi1sTAQEIBCAAAAAWBCAAAAAZBgoAAABlAG4ALQBVAFMAGwYKAAAAegBoAC0AQwBOABsGAAAAAAImBAAABXIAAAABVwAAAAQGBAAAAP9Oi1sFBgQAAAD/TotbBwYEAAAA/06LWwYGBAAAAP9Oi1sTAQIIBCAAAAAWBCAAAAAZBgoAAABlAG4ALQBVAFMAGwYKAAAAegBoAC0AQwBOAAgRAAAAAAwAAABwZVdbZ1I4bjpXb2YFcgAAAAE3AAAABAYEAAAA/06LWwUGBAAAAP9Oi1sHBgQAAAD/TotbBgYEAAAA/06LWxMBAggEIAAAABYEIAAAAAgxAAAAACwAAAAGXDhuqXOMVDhuD2LTfghUd41lZwz/GpDHj+OJHIwBMKJjIn1Je7llD18M/wWUAAAAAVcAAAAEBgQAAAD/TotbBQYEAAAA/06LWwcGBAAAAP9Oi1sGBgQAAAD/TotbEwECCAQgAAAAFgQgAAAAGQYKAAAAZQBuAC0AVQBTABsGCgAAAHoAaAAtAEMATgAIMwAAAAAuAAAAOk44bqJb0GObTwBOzXloUbBlhHbFZThuU0+Mmgz/KFc4bqlzx48Lei1O0GPYmgXoAAAAATcAAAAEBgQAAAD/TotbBQYEAAAA/06LWwcGBAAAAP9Oi1sGBgQAAAD/TotbEwECCAQgAAAAFgQgAAAACKcAAAAAogAAACh1N2KEdh1g9H79gJtSATDiVh+WT1NcT/2Am1KMVBtSsGX9gJtSAjAakMeP0GObTxpZN2gWU4R2Z1IsZ4xURWWLTsVggoIM/+Fus40NTgxUe3yLVyh1N2KEdgCXQmwM/xpZN2gWU4R2RWWLTsVggoKMVDhuD2Kpc9Vs405oiEB3DU4MVDBX31cBMA1ODFQRbM9lhHaHZRZTeXJygoxUvnxOUwVYAAAAAUcAAAAEBgQAAAD/TotbBQYEAAAA/06LWwcGBAAAAP9Oi1sGBgQAAAD/TotbEwECCAQgAAAAFgQgAAAAGwYKAAAAegBoAC0AQwBOAAgHAAAAAAIAAAAM/wWEAAAAAVcAAAAEBgQAAAD/TotbBQYEAAAA/06LWwcGBAAAAP9Oi1sGBgQAAAD/TotbEwECCAQgAAAAFgQgAAAAGQYKAAAAZQBuAC0AVQBTABsGCgAAAHoAaAAtAEMATgAIIwAAAAAeAAAAd1EJZ4OP2JqEdj55Gk/3TjxQjFSHZRZT9048UAIwBWEAAAABVwAAAAQGBAAAAP9Oi1sFBgQAAAD/TotbBwYEAAAA/06LWwYGBAAAAP9Oi1sTAQEIBCAAAAAWBCAAAAAZBgoAAABlAG4ALQBVAFMAGwYKAAAAegBoAC0AQwBOAAgAAAAABWEAAAABVwAAAAQGBAAAAP9Oi1sFBgQAAAD/TotbBwYEAAAA/06LWwYGBAAAAP9Oi1sTAQEIBCAAAAAWBCAAAAAZBgoAAABlAG4ALQBVAFMAGwYKAAAAegBoAC0AQwBOAAgAAAAACgAAAAAAAAAAEQAAAAAwAAAAABIAAAABBgAAAAAJBgAAAAAbBgAAAAABDwAAACgBBykBByoBBisBBRMBAQIAAAAA" style="border-style:none;margin-bottom:0pt;margin-top:0pt;mso-border-between:none;mso-border-bottom-alt:none;mso-border-left-alt:none;mso-border-right-alt:none;mso-border-top-alt:none;mso-pagination:none;text-align:justify;text-indent:32pt;"><span style="color:#000000;font-family:'仿宋';font-size:16pt;"><span style="mso-style-textfill-fill-color:#000000;">数字剧游场景主要面向5-12岁青少年及亲子家庭，在公园、景点、场馆、商业、乡村、古镇等各类场所制作开发“微信小程序+实景线索+剧情任务”形式的沉浸式剧本游戏活动，让亲子出行变得更有趣味性和知识性。通过活动，既可增进亲子关系，又能引导孩子锻炼体能、学习知识、训练思维、培养品格。真正做到寓教于乐、玩中收获。</span></span></p>
<p style="border-style:none;margin-bottom:0pt;margin-top:0pt;mso-border-between:none;mso-border-bottom-alt:none;mso-border-left-alt:none;mso-border-right-alt:none;mso-border-top-alt:none;mso-pagination:none;text-align:justify;text-indent:32pt;"><span style="color:#000000;font-family:'仿宋';font-size:16pt;"><span style="mso-style-textfill-fill-color:#000000;">实景数字剧游融入了剧情、游戏、解谜、实景和互动五个关键元素，孩子通过完成一系列任务，挑战自己的智慧和勇气，不仅让他们感受到冒险的刺激，还可以帮助他们提升解决问题的能力，增强团队合作的精神。实景数字剧游不仅仅是一款游戏，更是一款教育工具，旨在通过趣味的方式，引导孩子们走出家门探索真实的世界，锻炼他们的独立性和适应能力。</span></span></p>
<p style="border-style:none;margin-bottom:0pt;margin-top:0pt;mso-border-between:none;mso-pagination:none;text-align:justify;text-indent:32pt;"><span style="color:#000000;font-family:'仿宋';font-size:16pt;"><span style="mso-style-textfill-fill-color:#000000;">数字剧游场景将游玩和游戏结合起来，通过解谜、探索等方式，为游客提供一种全新的旅游体验，在游玩过程中提高用户的思维能力、团队协作能力和创新能力。通过提供多样化的剧本和故事情节，满足不同类型用户的需求，多样化的故事情节和游戏玩法代表着不同地域、不同民族的文化特色和精华，具有较高的社会价值和文化价值。</span></span></p>
<div style="display:flex;justify-content: center">
  <img style="max-width: 750px;" src="http://10.105.31.40:9001/img/1-2.png" alt="">
</div>
<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>
<p class="docData;DOCY;v5;3880;BQiAAgAAEYQCAAAGiAIAAAPmDgAABfQOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWgwAAABBAwAAAV0AAAABBgYAAAAmBMADAAAJBgAAAAAaBj8AAAAEBgQAAAD/TotbBQYEAAAA/06LWwcGBAAAAP9Oi1sGBgQAAAD/TotbEwECCAQgAAAAFgQgAAAAHAYCAAAAAAAbBgAAAAAC2gIAAAV4AAAAAVcAAAAEBgQAAAD/TotbBQYEAAAA/06LWwcGBAAAAP9Oi1sGBgQAAAD/TotbEwECCAQgAAAAFgQgAAAAGQYKAAAAZQBuAC0AVQBTABsGCgAAAHoAaAAtAEMATgAIFwAAAAASAAAACU5ZZZlecGVXW2dSOG46V29mBWQAAAABPwAAAAQGBAAAAP9Oi1sFBgQAAAD/TotbBwYEAAAA/06LWwYGBAAAAP9Oi1sTAQIIBCAAAAAWBCAAAAAcBgIAAAAAAAgbAAAAABYAAADlTq5f4U8PXAt6j15cTzpOZVHjUwz/BXAAAAABXwAAAAQGBAAAAP9Oi1sFBgQAAAD/TotbBwYEAAAA/06LWwYGBAAAAP9Oi1sTAQIIBCAAAAAWBCAAAAAZBgoAAABlAG4ALQBVAFMAGwYKAAAAegBoAC0AQwBOABwGAgAAAAAACAcAAAAAAgAAAAZcBd4AAAABPwAAAAQGBAAAAP9Oi1sFBgQAAAD/TotbBwYEAAAA/06LWwYGBAAAAP9Oi1sTAQIIBCAAAAAWBCAAAAAcBgIAAAAAAAiVAAAAAJAAAAC/fgpOOG4PYjpnNlIOTr9+C06eW29mLU6EdrpOATBpcgEwOldJe0NRIH34dtN+CFQM//RW1X5vZjpTh2UWUwEwhlPyUwEwIE/0i1VcAF/qgfFdhHZnUixnG1IPYQz/GpDHj4B7VVOEdk2Rbn8ATi6VH3UQYl5cjk7qgfFdhHZwZVdbZ1IsZzhuD1wLeo9eAjAFSQAAAAE/AAAABAYEAAAA/06LWwUGBAAAAP9Oi1sHBgQAAAD/TotbBgYEAAAA/06LWxMBAggEIAAAABYEIAAAABwGAgAAAAAACAAAAAAFSQAAAAE/AAAABAYEAAAA/06LWwUGBAAAAP9Oi1sHBgQAAAD/TotbBgYEAAAA/06LWxMBAggEIAAAABYEIAAAABwGAgAAAAAACAAAAAAAgQIAAAFdAAAAAQYGAAAAJgSAAgAACQYAAAAAGgY/AAAABAYEAAAA/06LWwUGBAAAAP9Oi1sHBgQAAAD/TotbBgYEAAAA/06LWxMBAggEIAAAABYEIAAAABwGAgAAAAAAGwYAAAAAAhoCAAAFdAAAAAFfAAAABAYEAAAA/06LWwUGBAAAAP9Oi1sHBgQAAAD/TotbBgYEAAAA/06LWxMBAggEIAAAABYEIAAAABkGCgAAAGUAbgAtAFUAUwAbBgoAAAB6AGgALQBDAE4AHAYCAAAAAAAICwAAAAAGAAAA7nZNUgz/BQABAAABPwAAAAQGBAAAAP9Oi1sFBgQAAAD/TotbBwYEAAAA/06LWwYGBAAAAP9Oi1sTAQIIBCAAAAAWBCAAAAAcBgIAAAAAAAi3AAAAALIAAAAnWdCPs2yHZcVlb2Y6UwBf0VOEdpaZ6JBwZVdbZ1IsZwoww3FvcEh5j3lLTtGRnGmYmA1UCzAM/7Bz8l3bj2VRv34LTp5bS202lrVrDP/li2dSLGeyi/CPhk4ATipOzk4Fbh1nf3qKjQyAZWeEdhwgtnJDUR0gDP8oV0l7hV/CU6BSv2vVi01Sq4gVXzBSGpDeXQlOWWWZXgz/QGLRUx91hHYATvt8F1JHWQJfbZBHkAIwBUkAAAABPwAAAAQGBAAAAP9Oi1sFBgQAAAD/TotbBwYEAAAA/06LWwYGBAAAAP9Oi1sTAQIIBCAAAAAWBCAAAAAcBgIAAAAAAAgAAAAABUkAAAABPwAAAAQGBAAAAP9Oi1sFBgQAAAD/TotbBwYEAAAA/06LWwYGBAAAAP9Oi1sTAQIIBCAAAAAWBCAAAAAcBgIAAAAAAAgAAAAAAAoEAAABbQAAAAEGBgAAACYEgAIAAAkGAAAAABoGTwAAAAQGBAAAAP9Oi1sFBgQAAAD/TotbBwYEAAAA/06LWwYGBAAAAP9Oi1sTAQIIBCAAAAAWBCAAAAAbBgoAAAB6AGgALQBDAE4AHAYCAAAAAAAbBgAAAAACkwMAAAV0AAAAAV8AAAAEBgQAAAD/TotbBQYEAAAA/06LWwcGBAAAAP9Oi1sGBgQAAAD/TotbEwECCAQgAAAAFgQgAAAAGQYKAAAAZQBuAC0AVQBTABsGCgAAAHoAaAAtAEMATgAcBgIAAAAAAAgLAAAAAAYAAAAqZ2VnDP8FYAAAAAE/AAAABAYEAAAA/06LWwUGBAAAAP9Oi1sHBgQAAAD/TotbBgYEAAAA/06LWxMBAggEIAAAABYEIAAAABwGAgAAAAAACBcAAAAAEgAAAPRW1X4nWdCPs2yHZcVlb2Y6UwV0AAAAAV8AAAAEBgQAAAD/TotbBQYEAAAA/06LWwcGBAAAAP9Oi1sGBgQAAAD/TotbEwECCAQgAAAAFgQgAAAAGQYKAAAAZQBuAC0AVQBTABsGCgAAAHoAaAAtAEMATgAcBgIAAAAAAAgLAAAAAAYAAAAGXAFj7X4FFgEAAAE/AAAABAYEAAAA/06LWwUGBAAAAP9Oi1sHBgQAAAD/TotbBgYEAAAA/06LWxMBAggEIAAAABYEIAAAABwGAgAAAAAACM0AAAAAyAAAAABf0VNBU+iQnltvZnBlV1tnUixnDP+GidZ2J1nQj7Nsh2XFZW9mOlMXUzpTATAtTjpTATBXUzpTDP+pizhuolvgZbqLcI0oV+pUKk46U99XDP/9kO9T5U4akMePrl/hTw9cC3qPXtuPZVGeW29mcGVXW2dSLGcM/yhXH3eeW4R2OldvZi1OomMifQEw44kcjAEwPnmkTpJOqFIM/x9hn2AnWdCPs2yGU/JThHbxbYOQATCHZRZThHaaU82RATAgT/SLhHZeeUdZBWAAAAABTwAAAAQGBAAAAP9Oi1sFBgQAAAD/TotbBwYEAAAA/06LWwYGBAAAAP9Oi1sTAQIIBCAAAAAWBCAAAAAbBgoAAAB6AGgALQBDAE4AHAYCAAAAAAAIBwAAAAACAAAAAjAFWQAAAAFPAAAABAYEAAAA/06LWwUGBAAAAP9Oi1sHBgQAAAD/TotbBgYEAAAA/06LWxMBAggEIAAAABYEIAAAABsGCgAAAHoAaAAtAEMATgAcBgIAAAAAAAgAAAAABVkAAAABTwAAAAQGBAAAAP9Oi1sFBgQAAAD/TotbBwYEAAAA/06LWwYGBAAAAP9Oi1sTAQIIBCAAAAAWBCAAAAAbBgoAAAB6AGgALQBDAE4AHAYCAAAAAAAIAAAAAAB6AgAAAWUAAAABBgYAAAAmBIACAAAJBgAAAAAaBkcAAAAEBgQAAAD/TotbBQYEAAAA/06LWwcGBAAAAP9Oi1sGBgQAAAD/TotbEwECCAQgAAAAFgQgAAAAGwYKAAAAegBoAC0AQwBOABsGAAAAAAILAgAABRwBAAABRwAAAAQGBAAAAP9Oi1sFBgQAAAD/TotbBwYEAAAA/06LWwYGBAAAAP9Oi1sTAQIIBCAAAAAWBCAAAAAbBgoAAAB6AGgALQBDAE4ACMsAAAAAxgAAAPJdCk6/foR2MgAqTmdSLGePlvZl71PlTihXCU5ZZZlej5b2ZWtiAXhTT4yaDP/YjwlnMQAqTmNrKFc2UlxPDP+EmKGLOQAIZzgA5WVNUgpOv34CMGRrFlkM//RW1X7Qj7Nsv2y4XNiPCWcJTipON2IWWWdSLGcM/01Pbn8GUitSKFcnWdCPs2zuaJdnbFHtVgEwJ1nQj7NsF1M6Uy1OOlO6TkyIZWtTkIxUIF+2W35u5FNHlQz/hJihi0FTAE5NUgpOv34CMBccAAAAAAQAAAAAAAAAAQ4AAABfAEcAbwBCAGEAYwBrAAUKAAAAAQAAAAAIAAAAABgJAAAAAAQAAAAAAAAABVEAAAABRwAAAAQGBAAAAP9Oi1sFBgQAAAD/TotbBwYEAAAA/06LWwYGBAAAAP9Oi1sTAQIIBCAAAAAWBCAAAAAbBgoAAAB6AGgALQBDAE4ACAAAAAAFUQAAAAFHAAAABAYEAAAA/06LWwUGBAAAAP9Oi1sHBgQAAAD/TotbBgYEAAAA/06LWxMBAggEIAAAABYEIAAAABsGCgAAAHoAaAAtAEMATgAIAAAAAAoAAAAAAAAAABEAAAAAMAAAAAASAAAAAQYAAAAACQYAAAAAGwYAAAAAAQ8AAAAoAQcpAQcqAQYrAQUTAQECAAAAAA==" style="border-style:none;margin-bottom:0pt;margin-top:0pt;mso-border-between:none;mso-border-bottom-alt:none;mso-border-left-alt:none;mso-border-right-alt:none;mso-border-top-alt:none;mso-pagination:none;text-align:justify;text-indent:48.00000000000001pt;"><span style="color:#000000;font-family:'仿宋';font-size:16pt;"><span style="mso-style-textfill-fill-color:#000000;">三教庙数字剧游场景以微信小程序作为入口，将线上游戏机制与线下实景中的人、物、场等元素相结合，围绕景区文化、历史、传说展开自己的剧本创意，通过简单的配置一键生成属于自己的数字剧本游小程序。</span></span></p>
<p style="border-style:none;margin-bottom:0pt;margin-top:0pt;mso-border-between:none;mso-border-bottom-alt:none;mso-border-left-alt:none;mso-border-right-alt:none;mso-border-top-alt:none;mso-pagination:none;text-align:justify;text-indent:32pt;"><span style="color:#000000;font-family:'仿宋';font-size:16pt;"><span style="mso-style-textfill-fill-color:#000000;">目前，大运河文旅景区开发的首部数字剧本《燃灯祈福之金榜题名》，现已进入线下实测阶段，该剧本讲述了一个从清朝穿越而来的“状元”，在等待参加殿试前被引到通州三教庙，所发生的一系列奇异遭遇。</span></span></p>
<p style="border-style:none;margin-bottom:0pt;margin-top:0pt;mso-border-between:none;mso-border-bottom-alt:none;mso-border-left-alt:none;mso-border-right-alt:none;mso-border-top-alt:none;mso-pagination:none;text-align:justify;text-indent:32pt;"><span style="color:#000000;font-family:'仿宋';font-size:16pt;"><span style="mso-style-textfill-fill-color:#000000;">未来，围绕大运河文旅景区将持续开发十部实景数字剧本，覆盖大运河文旅景区北区、中区、南区，让游客无论走在哪个区域，都可以通过微信小程序进入实景数字剧本，在真实的场景中探索、解谜、社交互动，感悟大运河历史的深邃、文化的厚重、传说的神奇。</span></span></p>
<p style="border-style:none;margin-bottom:0pt;margin-top:0pt;mso-border-between:none;mso-pagination:none;text-align:justify;text-indent:32pt;"><span style="color:#000000;font-family:'仿宋';font-size:16pt;"><span style="mso-style-textfill-fill-color:#000000;">已上线的2个剧本随时可以在三教庙随时扫码体验，还有1个正在制作，预计9月8日前上线。此外，围绕运河沿岸还有三个户外剧本，位置分别在大运河森林公园、大运河北区中区人行步道和张家湾古镇，预计十一前上线。</span></span></p>
<div style="display:flex;justify-content: center">
  <img style="max-width: 750px;" src="http://10.105.31.40:9001/img/1-3.png" alt="">
</div>
<p style="border-style:none;margin-bottom:0pt;margin-top:0pt;mso-border-between:none;mso-pagination:none;text-align:justify;text-indent:32pt;">&nbsp;</p>
    `,
    readCount: 100,
    createTime: '2023-09-08 14:30:00',
    updateTime: '2023-09-08 14:30:00'
  },
  {
    id: 2,
    title: '大运河“万舟骈集”数实融合文化体验场景',
    company: {
      id: 1,
      name: '北京嘉联科技有限公司'
    },
    summary:
      '掘大运河历史文化，使文化传承更生动直观，通过沉浸式体验，增强公众对中华民族精神的认同感，实现了对大运河历史文化资源更广泛的理解与传承，具有重要的社会效益。',
    coverImageUrl: 'http://10.105.31.40:9001/img/12.webp',
    headerImageUrl: new URL('@/assets/placeholder/productDefault.png', import.meta.url).href,
    status: ActiveStatus.Active,
    isOuterLink: false,
    content: `
    <p class="docData;DOCY;v5;1970;BQiAAgAAEYQCAAAGiAIAAANwBwAABX4HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5AQAAADfBAAAAVUAAAABBgYAAAAmBIACAAAJBgAAAAAaBjcAAAAEBgQAAAD/TotbBQYEAAAA/06LWwcGBAAAAP9Oi1sGBgQAAAD/TotbEwECCAQgAAAAFgQgAAAAGwYAAAAAAoAEAAAFbAAAAAFXAAAABAYEAAAA/06LWwUGBAAAAP9Oi1sHBgQAAAD/TotbBgYEAAAA/06LWxMBAggEIAAAABYEIAAAABkGCgAAAGUAbgAtAFUAUwAbBgoAAAB6AGgALQBDAE4ACAsAAAAABgAAAOWLOldvZgXYAQAAATcAAAAEBgQAAAD/TotbBQYEAAAA/06LWwcGBAAAAP9Oi1sGBgQAAAD/TotbEwECCAQgAAAAFgQgAAAACJcBAAAAkgEAAPpXjk41AEcAKwBNAEUAQwABMEEAUgAvAFYAUgBJe4BiL2cM/51PbmNrUx9mAF+QbnBlbmMM/2JfEGKGTidZ0I+zbBdTrE61a85OBmYOZlZuMFIgX7Zbfm44ADIAQ1NzfAEwQ1EOZgVuAGdBftt2a1F+dnReH2f0lYR2hlPyU4dlFlPhT29guXDld8aL/lYxjAz/U2IgkIZOJ1nQj7NsaFFvZqROkk4JTvR+cGVXWzBX/lYM/3ZeKVIodVgAUgCAYi9nDVmwc4ZOJ1nQj7NsDmYdUhwgB04fgoiaxpYdINt2b2YM/zhuolvvU4lseG0PX1NPjJpWAFIAOG7IiQz/QQBSANNiVVwnWdCPs2zhT29gDP9/eoqNhlPyU/Zl9JV0jwz/9HbCiR9h11MnWdCPs2zkU8pOh2UWU/lb1GsOTthTwY8CMCxneZjudg1OxU7QY0dThk5wZVdbz35ObQ5OnltTT89+Tm2Edo2HCFQM/3dRCWd/XttshHanThpOVICoUkhllF4M/wBnzZGBiYR2L2YM/wVqAAAAAVcAAAAEBgQAAAD/TotbBQYEAAAA/06LWwcGBAAAAP9Oi1sGBgQAAAD/TotbEwECCAQgAAAAFgQgAAAAGQYKAAAAZQBuAC0AVQBTABsGCgAAAHoAaAAtAEMATgAICQAAAAAEAAAAOldvZhccAAAAAAQAAAAAAAAAAQ4AAABfAEcAbwBCAGEAYwBrAAUKAAAAAQAAAAAIAAAAABgJAAAAAAQAAAAAAAAABfQAAAABNwAAAAQGBAAAAP9Oi1sFBgQAAAD/TotbBwYEAAAA/06LWwYGBAAAAP9Oi1sTAQIIBCAAAAAWBCAAAAAIswAAAACuAAAAGpDHj3BlV1sWU0titWvxbWVRFmOYYydZ0I+zbIZT8lOHZRZTDP9/T4dlFlMgT39i9GYfdahS9HbCiQz/GpDHj4lseG0PX1NPjJoM/55YOl9sURdP+VstTk5TEWzPZb58XnmEdqSLDFQfYQz/nluwc4ZO+VsnWdCPs2yGU/JTh2UWU0SNkG70Zn9e22yEdgZ044kOTiBPf2IM/3dRCWfNkYGJhHY+eRpPSGXKdgIwBUEAAAABNwAAAAQGBAAAAP9Oi1sFBgQAAAD/TotbBwYEAAAA/06LWwYGBAAAAP9Oi1sTAQIIBCAAAAAWBCAAAAAIAAAAAAVBAAAAATcAAAAEBgQAAAD/TotbBQYEAAAA/06LWwcGBAAAAP9Oi1sGBgQAAAD/TotbEwECCAQgAAAAFgQgAAAACAAAAAAKAAAAAAAAAAARAAAAADAAAAAAEgAAAAEGAAAAAAkGAAAAABsGAAAAAAEPAAAAKAEHKQEHKgEGKwEFEwEBAgAAAAA=" style="border-style:none;margin-bottom:0pt;margin-top:0pt;mso-border-between:none;mso-pagination:none;text-align:justify;text-indent:32pt;"><span style="color:#000000;font-family:'仿宋';font-size:16pt;"><span style="mso-style-textfill-fill-color:#000000;">该场景基于5G+MEC、AR/VR等技术，依据卫星开源数据，形成了大运河北京段从昆明湖到张家湾82千米、元明清最繁盛八百年期间的历史文化信息点知识图谱，打造了大运河全景交互三维数字地图，并利用XR技术复现了大运河明初“万舟骈集”盛景，游客可沉浸式体验VR游览，AR拓展大运河信息，穿越历史时间轴，直观感受大运河古今文化对比与变迁。本项目不仅提升了数字经济与实体经济的融合，具有广泛的产业联动效应，最重要的是，场景通过数字化手段深入挖掘大运河历史文化，使文化传承更生动直观，通过沉浸式体验，增强公众对中华民族精神的认同感，实现了对大运河历史文化资源更广泛的理解与传承，具有重要的社会效益</span></span></p>
<p>&nbsp;</p>
<div style="display:flex;justify-content: center">
  <img style="max-width: 750px;" src="http://10.105.31.40:9001/img/2-1.png" alt="">
</div>
<div style="display:flex;justify-content: center">
  <img style="max-width: 750px;" src="http://10.105.31.40:9001/img/2-2.png" alt="">
</div>
<div style="display:flex;justify-content: center">
  <img style="max-width: 750px;" src="http://10.105.31.40:9001/img/2-3.png" alt="">
</div>
<div style="display:flex;justify-content: center">
  <img style="max-width: 750px;" src="http://10.105.31.40:9001/img/2-4.png" alt="">
</div>
    `,
    readCount: 100,
    createTime: '2023-09-08 14:30:00',
    updateTime: '2023-09-08 14:30:00'
  },
  {
    id: 3,
    title: '马驹桥农文旅数字化场景',
    company: {
      id: 1,
      name: '北京嘉联科技有限公司'
    },
    summary:
      '场景通过数字人、AR、元宇宙等先进技术，为游客提供独特的马驹桥线上线下融合游览体验，打造沉浸式的智慧旅游环境。',
    coverImageUrl: 'http://10.105.31.40:9001/img/13.webp',
    headerImageUrl: new URL('@/assets/placeholder/productDefault.png', import.meta.url).href,
    status: ActiveStatus.Inactive,
    isOuterLink: true,
    link: 'https://www.baidu.com',
    readCount: 100,
    createTime: '2023-09-08 14:30:00',
    updateTime: '2023-09-08 14:30:00'
  }
]
